# renv bootstrap — generated by renv::init()
# This file is sourced automatically when the project is opened.
# Do NOT edit manually; run renv::init() to regenerate.

local({
  # Load renv from the project library if available, otherwise bootstrap
  renv_path <- Sys.getenv("RENV_PATH", unset = NA)
  if (is.na(renv_path)) {
    renv_path <- normalizePath("renv/library/R-4.3/x86_64-pc-linux-gnu/renv", mustWork = FALSE)
  }
  if (!file.exists(renv_path)) {
    # Bootstrap: install renv from CRAN
    message("renv not found — bootstrapping from CRAN ...")
    install.packages("renv", repos = "https://cloud.r-project.org")
  }
  library(renv, lib.loc = dirname(renv_path))
  renv::autoload()
})
